/**
 * ADDUS Platform — Role Based Permissions Matrix
 */

import { ROLES } from '../constants/index.js';

export const PERMISSIONS = {
  VIEW_CUSTOMER_DASHBOARD: [ROLES.CUSTOMER, ROLES.ADMIN, ROLES.SUPER_ADMIN],
  EDIT_BUSINESS_BRAIN: [ROLES.CUSTOMER, ROLES.ADMIN, ROLES.SUPER_ADMIN],
  SUBMIT_EXPERT_REVIEW: [ROLES.CUSTOMER],
  PUBLISH_EXPERT_REVIEW: [ROLES.ADMIN, ROLES.SUPER_ADMIN],
  VIEW_ADMIN_CONSOLE: [ROLES.ADMIN, ROLES.SUPER_ADMIN],
  VIEW_CREATOR_PORTAL: [ROLES.CREATOR, ROLES.ADMIN, ROLES.SUPER_ADMIN],
  ASSIGN_CREATOR: [ROLES.ADMIN, ROLES.SUPER_ADMIN],
  VIEW_ALL_PROJECTS: [ROLES.ADMIN, ROLES.SUPER_ADMIN],
};

export function hasPermission(role, permissionKey) {
  const allowedRoles = PERMISSIONS[permissionKey] || [];
  return allowedRoles.includes(role);
}
